version: '{build}'

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - COMPILER: "gcc"
    PLATFORM: "mingw64"
  - COMPILER: "gcc"
    PLATFORM: "mingw32"
  - COMPILER: "gcc"
    PLATFORM: "clang"

install:
  - ECHO Installing %COMPILER% %PLATFORM% %CONFIGURATION%
  - MKDIR bin
  - if [%COMPILER%]==[gcc] SET PATH_ORIGINAL=%PATH%
  - if [%COMPILER%]==[gcc] (
      SET "PATH_MINGW32=c:\MinGW\bin;c:\MinGW\usr\bin" &&
      SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin" &&
      COPY C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe &&
      COPY C:\MinGW\bin\gcc.exe C:\MinGW\bin\cc.exe
    ) else (
      IF [%PLATFORM%]==[x64] (SET ADDITIONALPARAM=/p:LibraryPath="C:\Program Files\Microsoft SDKs\Windows\v7.1\lib\x64;c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\lib\amd64;")
    )

matrix:
  # If at least one job has failed the entire build is marked as failed
  fast_finish: true

build_script:
  - if [%PLATFORM%]==[mingw32] (
      SET PATH=%PATH_MINGW32%;%PATH_ORIGINAL%
    ) else (
      SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL%
    )
  - ECHO *** &&
      ECHO Building %COMPILER% %PLATFORM% %CONFIGURATION% &&
      ECHO ***
  - if [%PLATFORM%]==[clang] (clang -v)
  - if [%COMPILER%]==[gcc] (gcc -v)
  - if [%COMPILER%]==[gcc] (
      echo ----- &&
      make -v &&
      echo ----- &&
      make
    )
  

# email notifications set at https://ci.appveyor.com/notifications 