matrix:
 include:
  # Ubuntu 16.04 LTS (Xenial Xerus)
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc

  # Ubuntu 18.04 LTS (Bionic Beaver)
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc

  # OS X  
  - os: osx
    sudo: required
    compiler: clang

script:
  # build library and tests, install library
  - mkdir -v build 
  - cd build
  - echo $(pwd)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      gcc -v;
    else
      clang -v;
    fi
  - make;
  - make unit_test

notifications:
  email: true