matrix:
 include:
  # Ubuntu 16.04 LTS (Xenial Xerus)
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc

  # Ubuntu 18.04 LTS (Bionic Beaver)
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc

  # OS X  
  - os: osx
    sudo: required
    compiler: clang

script:
  - echo $(pwd)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      gcc -v;
    else
      clang -v;
    fi
  - make;
  # - make unit_test
  # unit_test.c:13:10: error: variable ‘pause’ set but not used [-Werror=unused-but-set-variable]
  #    char pause;
  # This had been used to allow reading the result of the test w/o the terminal closing.  leaving it as-is
  

notifications:
  email: true